#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Apr 28 14:28:19 CST 2026
maven-metadata-ApacheSnapshot.xml.error=
maven-metadata-ApacheSnapshot.xml.lastUpdated=1777357699258
